// ---------------------------------------------------------------------------
// MMC Main — Mesh-Based Monte Carlo for fNIRS amygdala simulation
// ---------------------------------------------------------------------------
// Usage:
//   mmc_fnirs --mesh mni152_head.mmcmesh [options]
//
// Options:
//   --mesh     <file>   MMC mesh file (generated by generate_mni152_mesh.py)
//   --photons  <N>      Photons per wavelength (default: 100e6)
//   --output   <dir>    Output directory (default: results/)
//   --wavelengths 730 850  Wavelengths in nm (default: 730 850)
//   --seed     <N>      RNG seed (default: 42)
// ---------------------------------------------------------------------------

#include "mmc_geometry.h"
#include "mmc_kernel.cuh"
#include "optical_properties.cuh"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <string>
#include <vector>
#include <algorithm>
#include <chrono>
#include <cuda_runtime.h>

#define CUDA_CHECK(call) do {                                        \
    cudaError_t _e = (call);                                         \
    if (_e != cudaSuccess) {                                         \
        fprintf(stderr, "CUDA error %s:%d: %s\n",                   \
                __FILE__, __LINE__, cudaGetErrorString(_e));         \
        exit(1);                                                     \
    }                                                                \
} while(0)

// ---------------------------------------------------------------------------
// Detector layout in MNI152 space (mm)
// Source: right temporal bone, projecting from amygdala center (+24,-2,-20)
// Primary axis: inferior-posterior along temporal surface
// ---------------------------------------------------------------------------
static std::vector<Detector> build_mni152_detectors(const float src[3], float det_radius)
{
    std::vector<Detector> dets;

    // Source-detector axis along scalp (inferior-posterior temporal direction in MNI)
    // Approximate tangent on temporal scalp from MNI source position
    float axis[3] = {-0.1f, -0.7f, -0.7f};
    float len = sqrtf(axis[0]*axis[0]+axis[1]*axis[1]+axis[2]*axis[2]);
    axis[0]/=len; axis[1]/=len; axis[2]/=len;

    // Orthogonal axis (lateral)
    float lat[3] = {-0.99f, 0.07f, 0.07f};

    // Short-separation channels (superficial signal regression)
    float sds_short[] = {8.0f};
    // Primary long-SDS channels
    float sds_primary[] = {15.f,20.f,25.f,30.f,32.f,35.f,38.f,40.f,45.f};
    // Off-axis at ±20°
    float sds_off[]   = {20.f,25.f,30.f,35.f,40.f};
    float angles_deg[] = {-30.f, 30.f};

    int id = 0;
    auto add = [&](float sds, float ang_deg) {
        float ang = ang_deg * (float)M_PI / 180.f;
        float ca = cosf(ang), sa = sinf(ang);
        Detector d;
        d.x = src[0] + sds*(ca*axis[0] + sa*lat[0]);
        d.y = src[1] + sds*(ca*axis[1] + sa*lat[1]);
        d.z = src[2] + sds*(ca*axis[2] + sa*lat[2]);
        d.radius = det_radius;
        d.id = id++;
        
        // Surface normal: radial direction from head center (MNI origin)
        // Head ellipsoid approx: 78mm x 95mm x 85mm
        // Normal is direction from center scaled by inverse ellipsoid radii
        float rx = d.x / 78.0f, ry = d.y / 95.0f, rz = d.z / 85.0f;
        float r_mag = sqrtf(rx*rx + ry*ry + rz*rz);
        if (r_mag > 1e-6f) {
            d.nx = rx / r_mag;
            d.ny = ry / r_mag;
            d.nz = rz / r_mag;
        } else {
            d.nx = d.ny = 0.0f; d.nz = 1.0f;
        }
        
        // Critical angle: photons with dot(dir, normal) < n_critical are rejected
        // n_air / n_scalp ≈ 1.0 / 1.4 ≈ 0.714
        d.n_critical = 1.0f / 1.4f;
        
        dets.push_back(d);
    };

    for (float s : sds_short)   add(s, 0.f);
    for (float s : sds_primary) add(s, 0.f);
    for (float ang : angles_deg)
        for (float s : sds_off)
            add(s, ang);

    printf("Created %d detectors (radius=%.1f mm) with angular acceptance\n", 
           (int)dets.size(), det_radius);
    return dets;
}

// ---------------------------------------------------------------------------
// Default time gates (same as voxel MC, optimized for amygdala window)
// ---------------------------------------------------------------------------
static void build_time_gates(MMCConfig& cfg)
{
    // 10 gates: early (superficial) + late (deep amygdala window 2-4.5 ns)
    float gates[NUM_TIME_GATES][2] = {
        {   0.f,  500.f},  // 0-0.5 ns
        { 500.f, 1000.f},  // 0.5-1 ns
        {1000.f, 1500.f},  // 1-1.5 ns
        {1500.f, 2000.f},  // 1.5-2 ns
        {2000.f, 2500.f},  // 2-2.5 ns  <- amygdala sensitivity begins
        {2500.f, 3000.f},  // 2.5-3 ns
        {3000.f, 3500.f},  // 3-3.5 ns  <- peak amygdala sensitivity
        {3500.f, 4000.f},  // 3.5-4 ns
        {4000.f, 4500.f},  // 4-4.5 ns
        {4500.f, 5000.f},  // 4.5-5 ns
    };
    cfg.num_gates = NUM_TIME_GATES;
    for (int g = 0; g < NUM_TIME_GATES; g++) {
        cfg.gate_start_ps[g] = gates[g][0];
        cfg.gate_end_ps[g]   = gates[g][1];
    }
}

// ---------------------------------------------------------------------------
// Save results to JSON (same format as voxel MC)
// ---------------------------------------------------------------------------
static void save_results_json(
    const std::string& path, float wavelength_nm,
    const std::vector<Detector>& dets,
    const std::vector<double>& det_weight,
    const std::vector<double>& det_pathlength,
    const std::vector<unsigned long long>& det_count,
    const std::vector<double>& gated_weight,
    const std::vector<double>& gated_pathlength,
    uint64_t num_photons)
{
    FILE* f = fopen(path.c_str(), "w");
    if (!f) { fprintf(stderr,"Cannot write %s\n",path.c_str()); return; }

    int nd = (int)dets.size();
    fprintf(f, "{\n");
    fprintf(f, "  \"wavelength_nm\": %.1f,\n", wavelength_nm);
    fprintf(f, "  \"num_photons\": %llu,\n", (unsigned long long)num_photons);
    fprintf(f, "  \"method\": \"mmc\",\n");
    fprintf(f, "  \"detectors\": [\n");

    const char* tnames[] = {"air","scalp","skull","csf","gray","white","amygdala"};

    for (int d = 0; d < nd; d++) {
        double w = det_weight[d];
        unsigned long long cnt = det_count[d];
        fprintf(f, "    {\n");
        fprintf(f, "      \"id\": %d,\n", dets[d].id);
        fprintf(f, "      \"x_mm\": %.3f, \"y_mm\": %.3f, \"z_mm\": %.3f,\n",
                dets[d].x, dets[d].y, dets[d].z);
        fprintf(f, "      \"sds_mm\": %.2f,\n",
                sqrtf(0.f)); // filled below
        fprintf(f, "      \"cw_weight\": %.6e,\n", w);
        fprintf(f, "      \"num_detected\": %llu,\n", cnt);
        fprintf(f, "      \"partial_pathlength_mm\": {");
        for (int t = 0; t < NUM_TISSUE_TYPES; t++) {
            fprintf(f, "\"%s\": %.6f%s",
                    tnames[t], det_pathlength[d*NUM_TISSUE_TYPES+t],
                    (t<NUM_TISSUE_TYPES-1)?", ":"");
        }
        fprintf(f, "},\n");
        fprintf(f, "      \"time_gates\": [\n");
        for (int g = 0; g < NUM_TIME_GATES; g++) {
            fprintf(f, "        {\"gate\": %d, \"weight\": %.6e, \"pathlength\": {",
                    g, gated_weight[d*NUM_TIME_GATES+g]);
            int base = (d*NUM_TIME_GATES+g)*NUM_TISSUE_TYPES;
            for (int t = 0; t < NUM_TISSUE_TYPES; t++) {
                fprintf(f, "\"%s\": %.6f%s",
                        tnames[t], gated_pathlength[base+t],
                        (t<NUM_TISSUE_TYPES-1)?", ":"");
            }
            fprintf(f, "}}%s\n", (g<NUM_TIME_GATES-1)?",":"");
        }
        fprintf(f, "      ]\n");
        fprintf(f, "    }%s\n", (d<nd-1)?",":"");
    }
    fprintf(f, "  ]\n}\n");
    fclose(f);
    printf("Saved %s\n", path.c_str());
}

// ---------------------------------------------------------------------------
// Run one wavelength simulation
// ---------------------------------------------------------------------------
static void run_wavelength(
    MMCMeshDevice& dev_mesh, const MMCMeshHost& host_mesh,
    const std::vector<Detector>& dets,
    float wavelength_nm,
    uint64_t num_photons,
    unsigned long long seed,
    const std::string& out_dir,
    int block_size, int num_blocks)
{
    int nd = (int)dets.size();

    // Optical properties
    OpticalProps props[NUM_TISSUE_TYPES];
    compute_optical_properties(wavelength_nm, props);

    printf("\n--- Wavelength %.0f nm ---\n", wavelength_nm);
    for (int t = 0; t < NUM_TISSUE_TYPES; t++) {
        printf("  tissue[%d]: mu_a=%.4f  mu_s=%.4f  g=%.3f  n=%.3f\n",
               t, props[t].mu_a, props[t].mu_s, props[t].g, props[t].n);
    }

    // Source in MNI152 space — right temporal projecting toward amygdala
    // Right amygdala centroid (MNI): ~(+24, -2, -20) mm
    // Project outward to scalp surface along the lateral-inferior direction
    float amyg_center[3] = {24.f, -2.f, -20.f};
    float src_dir_unnorm[3] = {
        host_mesh.bbox_max[0]*0.9f - amyg_center[0],
        -8.f - amyg_center[1],
        -10.f - amyg_center[2]
    };
    float src_len = sqrtf(src_dir_unnorm[0]*src_dir_unnorm[0]
                        + src_dir_unnorm[1]*src_dir_unnorm[1]
                        + src_dir_unnorm[2]*src_dir_unnorm[2]);
    // Source position: on scalp surface ~55mm from amygdala (preauricular)
    float src_pos[3] = {
        amyg_center[0] + 55.f * src_dir_unnorm[0] / src_len,
        amyg_center[1] + 55.f * src_dir_unnorm[1] / src_len,
        amyg_center[2] + 55.f * src_dir_unnorm[2] / src_len
    };
    // Inward direction (toward amygdala)
    float src_dir[3] = {
        -src_dir_unnorm[0]/src_len,
        -src_dir_unnorm[1]/src_len,
        -src_dir_unnorm[2]/src_len
    };
    printf("Source: (%.1f, %.1f, %.1f) mm  dir: (%.3f, %.3f, %.3f)\n",
           src_pos[0], src_pos[1], src_pos[2],
           src_dir[0], src_dir[1], src_dir[2]);

    // Build MMCConfig
    MMCConfig cfg;
    cfg.num_photons = num_photons;
    memcpy(cfg.src_pos, src_pos, 3*sizeof(float));
    memcpy(cfg.src_dir, src_dir, 3*sizeof(float));
    cfg.beam_radius      = 7.5f;    // 15 mm diameter disk
    cfg.src_elem         = find_source_element(host_mesh, src_pos);
    cfg.weight_threshold = 1e-4f;
    cfg.roulette_m       = 10;
    memcpy(cfg.tissue_props, props, sizeof(props));
    cfg.tpsf_bins   = TPSF_BINS;
    cfg.tpsf_bin_ps = TPSF_BIN_PS;
    build_time_gates(cfg);

    printf("Source element: %d  (tissue=%d)\n", cfg.src_elem,
           (cfg.src_elem>=0) ? host_mesh.tissue[cfg.src_elem] : -1);

    // Allocate detector output buffers
    size_t det_w_sz   = nd * sizeof(double);
    size_t det_pl_sz  = nd * NUM_TISSUE_TYPES * sizeof(double);
    size_t det_cnt_sz = nd * sizeof(unsigned long long);
    size_t tpsf_sz    = nd * TPSF_BINS * sizeof(float);
    size_t gw_sz      = nd * NUM_TIME_GATES * sizeof(double);
    size_t gpl_sz     = nd * NUM_TIME_GATES * NUM_TISSUE_TYPES * sizeof(double);

    double*             d_det_weight;
    double*             d_det_pl;
    unsigned long long* d_det_count;
    float*              d_tpsf;
    double*             d_gated_w;
    double*             d_gated_pl;

    CUDA_CHECK(cudaMalloc(&d_det_weight, det_w_sz));
    CUDA_CHECK(cudaMalloc(&d_det_pl,     det_pl_sz));
    CUDA_CHECK(cudaMalloc(&d_det_count,  det_cnt_sz));
    CUDA_CHECK(cudaMalloc(&d_tpsf,       tpsf_sz));
    CUDA_CHECK(cudaMalloc(&d_gated_w,    gw_sz));
    CUDA_CHECK(cudaMalloc(&d_gated_pl,   gpl_sz));

    CUDA_CHECK(cudaMemset(d_det_weight, 0, det_w_sz));
    CUDA_CHECK(cudaMemset(d_det_pl,     0, det_pl_sz));
    CUDA_CHECK(cudaMemset(d_det_count,  0, det_cnt_sz));
    CUDA_CHECK(cudaMemset(d_tpsf,       0, tpsf_sz));
    CUDA_CHECK(cudaMemset(d_gated_w,    0, gw_sz));
    CUDA_CHECK(cudaMemset(d_gated_pl,   0, gpl_sz));

    // Detectors on GPU
    Detector* d_detectors;
    CUDA_CHECK(cudaMalloc(&d_detectors, nd * sizeof(Detector)));
    CUDA_CHECK(cudaMemcpy(d_detectors, dets.data(), nd*sizeof(Detector),
                          cudaMemcpyHostToDevice));

    // RNG states
    int total_threads = num_blocks * block_size;
    curandState* d_rng;
    CUDA_CHECK(cudaMalloc(&d_rng, total_threads * sizeof(curandState)));
    mmc_init_rng<<<num_blocks, block_size>>>(d_rng, seed, total_threads);
    CUDA_CHECK(cudaGetLastError());

    printf("Launching %d blocks × %d threads = %d threads  (%llu photons)\n",
           num_blocks, block_size, total_threads, (unsigned long long)num_photons);

    // Progress bar setup - use smaller batches for more frequent updates
    int num_batches = 100;  // More batches = more frequent updates
    uint64_t photons_per_batch = (num_photons + num_batches - 1) / num_batches;
    
    auto t_start = std::chrono::high_resolution_clock::now();
    
    printf("\nProgress (batches: %d, photons/batch: %llu):\n", num_batches, (unsigned long long)photons_per_batch);
    printf("  [                              ]   0.0%%  Starting...");
    fflush(stdout);
    
    for (int batch = 0; batch < num_batches; batch++) {
        // Update config for this batch
        MMCConfig batch_cfg = cfg;
        batch_cfg.num_photons = photons_per_batch;
        
        // Update seed for each batch
        uint64_t batch_seed = seed + batch;
        mmc_init_rng<<<num_blocks, block_size>>>(d_rng, batch_seed, total_threads);
        CUDA_CHECK(cudaGetLastError());
        
        // Launch batch
        mmc_photon_kernel<<<num_blocks, block_size>>>(
            dev_mesh, batch_cfg,
            d_detectors, nd,
            d_det_weight, d_det_pl, d_det_count,
            d_tpsf, d_gated_w, d_gated_pl,
            d_rng);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
        
        // Progress update every 5 batches or on last batch
        if ((batch + 1) % 5 == 0 || batch == num_batches - 1) {
            auto t_now = std::chrono::high_resolution_clock::now();
            double elapsed = std::chrono::duration<double>(t_now - t_start).count();
            double pct = 100.0 * (batch + 1) / num_batches;
            uint64_t photons_done = (uint64_t)(batch + 1) * photons_per_batch;
            photons_done = (photons_done > num_photons) ? num_photons : photons_done;
            double rate = photons_done / elapsed / 1e6;
            double eta = (batch + 1 > 0) ? elapsed * (num_batches - batch - 1) / (batch + 1) : 0;
            
            int bar_width = 30;
            int filled = (int)(bar_width * pct / 100.0);
            
            // Use newline every 5% for visibility with tee
            printf("\r  [");
            for (int i = 0; i < bar_width; i++)
                printf("%s", i < filled ? "#" : "-");
            printf("] %5.1f%%  %.1f Mph/s", pct, rate);
            if (eta > 60.0)
                printf("  ETA %dm%02ds", (int)(eta / 60), (int)eta % 60);
            else
                printf("  ETA %ds", (int)eta);
            fflush(stdout);
        }
    }
    printf("\nKernel done.\n");

    // Copy results back
    std::vector<double>             h_det_weight(nd);
    std::vector<double>             h_det_pl(nd * NUM_TISSUE_TYPES);
    std::vector<unsigned long long> h_det_count(nd);
    std::vector<float>              h_tpsf(nd * TPSF_BINS);
    std::vector<double>             h_gated_w(nd * NUM_TIME_GATES);
    std::vector<double>             h_gated_pl(nd * NUM_TIME_GATES * NUM_TISSUE_TYPES);

    CUDA_CHECK(cudaMemcpy(h_det_weight.data(), d_det_weight, det_w_sz, cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(h_det_pl.data(),     d_det_pl,     det_pl_sz,  cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(h_det_count.data(),  d_det_count,  det_cnt_sz, cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(h_tpsf.data(),       d_tpsf,       tpsf_sz,    cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(h_gated_w.data(),    d_gated_w,    gw_sz,      cudaMemcpyDeviceToHost));
    CUDA_CHECK(cudaMemcpy(h_gated_pl.data(),   d_gated_pl,   gpl_sz,     cudaMemcpyDeviceToHost));

    // Print quick summary
    printf("Detections: ");
    for (int d = 0; d < nd && d < 8; d++)
        printf("d%d=%llu  ", d, h_det_count[d]);
    printf("...\n");

    // Save JSON
    char tag[16];
    snprintf(tag, sizeof(tag), "%.0f", wavelength_nm);
    save_results_json(out_dir + "/mmc_results_" + tag + "nm.json",
                      wavelength_nm, dets,
                      h_det_weight, h_det_pl, h_det_count,
                      h_gated_w, h_gated_pl, num_photons);

    // Save TPSF binary
    {
        std::string tpsf_path = out_dir + "/mmc_tpsf_" + tag + "nm.bin";
        FILE* tf = fopen(tpsf_path.c_str(), "wb");
        if (tf) { fwrite(h_tpsf.data(), sizeof(float), h_tpsf.size(), tf); fclose(tf); }
        printf("Saved %s\n", tpsf_path.c_str());
    }

    cudaFree(d_det_weight); cudaFree(d_det_pl); cudaFree(d_det_count);
    cudaFree(d_tpsf); cudaFree(d_gated_w); cudaFree(d_gated_pl);
    cudaFree(d_detectors); cudaFree(d_rng);
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char* argv[])
{
    // Defaults
    std::string mesh_path   = "mni152_head.mmcmesh";
    std::string out_dir     = "results";
    uint64_t    num_photons = 100000000ULL;
    unsigned long long seed = 42;
    std::vector<float> wavelengths = {730.f, 850.f};

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i],"--mesh")   && i+1<argc) mesh_path   = argv[++i];
        else if (!strcmp(argv[i],"--output") && i+1<argc) out_dir = argv[++i];
        else if (!strcmp(argv[i],"--photons")&& i+1<argc) num_photons = (uint64_t)atoll(argv[++i]);
        else if (!strcmp(argv[i],"--seed")  && i+1<argc) seed = (unsigned long long)atoll(argv[++i]);
        else if (!strcmp(argv[i],"--wavelengths")) {
            wavelengths.clear();
            while (i+1<argc && argv[i+1][0]!='-')
                wavelengths.push_back((float)atof(argv[++i]));
        }
    }

    printf("=== MMC fNIRS — MNI152 Head ===\n");
    printf("Mesh:      %s\n", mesh_path.c_str());
    printf("Output:    %s\n", out_dir.c_str());
    printf("Photons:   %llu\n", (unsigned long long)num_photons);
    printf("Wavelengths:");
    for (float w : wavelengths) printf(" %.0f nm", w);
    printf("\n");

    // GPU info
    int dev; cudaDeviceProp prop;
    CUDA_CHECK(cudaGetDevice(&dev));
    CUDA_CHECK(cudaGetDeviceProperties(&prop, dev));
    printf("GPU: %s  (SM %d.%d, %zu MB)\n",
           prop.name, prop.major, prop.minor,
           prop.totalGlobalMem>>20);

    int block_size = 256;
    int num_blocks = prop.multiProcessorCount * 32;

    // Load mesh
    MMCMeshHost host_mesh = load_mmc_mesh(mesh_path);
    GridData    grid      = build_spatial_grid(host_mesh);
    MMCMeshDevice dev_mesh = upload_mmc_mesh(host_mesh, grid);

    // Compute actual source position (same as run_wavelength)
    float amyg_center[3] = {24.f, -2.f, -20.f};
    float src_dir_unnorm[3] = {
        host_mesh.bbox_max[0]*0.9f - amyg_center[0],
        -8.f - amyg_center[1],
        -10.f - amyg_center[2]
    };
    float src_len = sqrtf(src_dir_unnorm[0]*src_dir_unnorm[0]
                        + src_dir_unnorm[1]*src_dir_unnorm[1]
                        + src_dir_unnorm[2]*src_dir_unnorm[2]);
    float src_pos[3] = {
        amyg_center[0] + 55.f * src_dir_unnorm[0] / src_len,
        amyg_center[1] + 55.f * src_dir_unnorm[1] / src_len,
        amyg_center[2] + 55.f * src_dir_unnorm[2] / src_len
    };
    
    // Build detectors relative to ACTUAL source position
    std::vector<Detector> dets = build_mni152_detectors(src_pos, 4.0f);
    printf("Built %d detectors around source (%.1f, %.1f, %.1f)\n", 
           (int)dets.size(), src_pos[0], src_pos[1], src_pos[2]);

    // Run each wavelength
    for (float wl : wavelengths) {
        run_wavelength(dev_mesh, host_mesh, dets, wl,
                       num_photons, seed++, out_dir,
                       block_size, num_blocks);
    }

    free_mmc_mesh_gpu();
    printf("\nDone.\n");
    return 0;
}
