/**
 * @file mesh_loader.h
 * @brief MNI152 tetrahedral mesh loader for MMC simulation.
 * 
 * Loads .mmcmesh files generated by generate_mni152_mesh.py into GPU memory.
 */

#pragma once

#include "types.h"
#include <vector>
#include <string>

namespace mmc {

/**
 * @brief CPU-side mesh storage.
 */
struct Mesh {
    std::vector<float3> nodes;           // Node positions
    std::vector<Tetrahedron> elems;      // Tetrahedral elements
    float3 bbox_min;                     // Bounding box
    float3 bbox_max;
    
    bool load_from_file(const std::string& path);
    void print_stats() const;
    
    // Compute element properties
    float compute_volume(int elem_idx) const;
    float3 compute_centroid(int elem_idx) const;
    void compute_bounding_box();
};

/**
 * @brief GPU mesh representation (device pointers).
 */
struct GPUMesh {
    float3* nodes;           // Device pointer to nodes
    Tetrahedron* elems;      // Device pointer to elements
    int32_t num_nodes;
    int32_t num_elems;
    float3 bbox_min;
    float3 bbox_max;
    
    void allocate(const Mesh& cpu_mesh);
    void free();
    void copy_from_cpu(const Mesh& cpu_mesh);
};

/**
 * @brief Initialize mesh on GPU from file.
 * 
 * @param mesh_path Path to .mmcmesh file
 * @param gpu_mesh Output GPU mesh structure
 * @return true on success
 */
bool init_mesh(const std::string& mesh_path, GPUMesh& gpu_mesh);

/**
 * @brief Find initial tetrahedron for photon launch.
 * 
 * Uses bounding box acceleration to find which tetrahedron contains the point.
 * 
 * @param pos Position in mm
 * @param mesh GPU mesh
 * @return Tetrahedron index or -1 if outside
 */
__device__ int32_t find_containing_tet(const float3& pos, const GPUMesh& mesh);

/**
 * @brief Barycentric coordinate test for point-in-tet.
 */
__device__ bool point_in_tet(const float3& p, const float3& v0, 
                              const float3& v1, const float3& v2, 
                              const float3& v3, float& u, float& v, float& w);

} // namespace mmc
